site_name: DevOps Docs
site_description: Documentations autour de la CI/CD et de Github
site_url: http://localhost
site_author: Aurelien

repo_name: o-devops/doc
repo_url: https://github.com/o-devops/doc

copyright: Retrouvez toute les formations O'clock sur <a href=https://oclock.io>le site oclock.io</a>

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  language: 'fr'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.footer
    - navigation.top
    - header.autohide

nav:
  - Accueil: /doc/
  - Github:
    - Gestion de compte: github/account.md
    - Les hooks git: github/git-hooks.md
    - Introduction à Github Action: github/ga-intro.md
    - Le local runner: github/ga-local-runner.md
    - Merge PR: github/merge.md
    - Github pages: github/ga-github-pages.md
    - Les variables et secrets: github/ga-vars-and-secrets.md
    - Les matrices: github/ga-matrix.md
    - Produire des images avec Github: github/ga-docker-push.md
  - Markdown:
    - Les textes: markdown/Texte.md
    - Le code: markdown/Code.md
    - Les tableaux: markdown/tableaux.md
  - Docker:
    - Les bases: docker/docker-basics.md
  - Ansible:
    - Introduction à Ansible: ansible/intro.md
  - Git:
    - Utilisation des tags: git/git-tag.md
    - Produire des images avec Github: github/ga-docker-push.md
  - AWS:
    - Introduction: aws/aws-intro.md
    - La documentation: aws/aws-doc.md
    - Les coûts AWS: aws/aws-cost.md
    - IAM: aws/aws-iam.md
  - Terraform:
    - Introduction: terraform/terraform-intro.md
  - Linux:
    - Le gestionnaire de paquet snap: linux/snap.md
  - Tutoriels:
    - Un site web avec Linux et Docker: tutoriels/website-with-linux-docker.md

markdown_extensions:
  #- mdx_truly_sane_lists # for mkdocs to indent nested lists with 2 spaces VS 4 by default
  #- pymdownx.tabbed
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.magiclink
  #- pymdownx.saneheaders
  - pymdownx.smartsymbols
  #- footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
plugins:
  - tags
  - search:
      prebuild_index: false
  - git-revision-date-localized:
      enable_creation_date: true

extra_css:
  - _assets/stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - _assets/javascript/tables.js
